########### Users ###############

########### Products ###############

###
POST http://localhost:5000/api/v1/products
Content-Type: application/json

{
  "name":"AMY SS14R - DRAGON EYES",
  "image":"https://res.cloudinary.com/dtggdx3hc/image/upload/v1648048426/ss15_sort_1000x1000_fnmfr3.jpg",
  "price":1299
}

###
GET http://localhost:5000/api/v1/products

###
DELETE http://localhost:5000/api/v1/products/62571d804dcaf8e80128484c
Authorization: Bearer 


########### OrderLines ###############

###
POST http://localhost:5000/api/v1/orderLines/6229f8d34f07b73d003e72e9
Content-Type: application/json

{
  "price":"1.99"
}

###
POST http://localhost:5000/api/v1/orderLines/623b3a7384b9baf1109053fa
Content-Type: application/json

{
  "quantity":"1",
  "price":"1350"
}

###
PUT http://localhost:5000/api/v1/orderLines/623b3a7384b9baf1109053fa
Content-Type: application/json

{
  "quantity":"10",
  "price": "10000"
}

###
GET http://localhost:5000/api/v1/orderLines/62326179b9c85d3fc833d686


###
DELETE http://localhost:5000/api/v1/orderLines/625729c3036894081cba712c

###
DELETE http://localhost:5000/api/v1/orderLines/all/62326179b9c85d3fc833d686

########### Orders ###############

###
POST http://localhost:5000/api/v1/orders/62326179b9c85d3fc833d686
Content-Type: application/json

{
  "orderedlines":[
      {"_id": "6251be4d4186c34788e4f034"},
      {"_id": "6251be494186c34788e4f030"}
  ],
  "totalPrice":"121.99"
}

###
GET http://localhost:5000/api/v1/orders/62326179b9c85d3fc833d686