########### Users ###############

###
POST http://localhost:5000/api/v1/users
Content-Type: application/json

{
  "email":"r_geo6@gmail.com",
  "username": "Rgeor6",
  "password": "12344321",
  "firstName": "Rafael",
  "lastName": "Georgio"
}

###

POST http://localhost:5000/api/v1/users/login HTTP/1.1
Content-Type: application/json

{
  "email":"r_geo5@gmail.com",
  "password": "12344321"
}

###

POST http://localhost:5000/api/v1/users/login HTTP/1.1
Content-Type: application/json

{
  "username": "Rgeor6",
  "password": "12344321"
}

###
GET http://localhost:5000/api/v1/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjJiYjE2MDViODNhODBiMDBmMmJmMGIiLCJlbWFpbCI6InJfZ2VvNUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6IlJnZW9yZ3NlIiwiaWF0IjoxNjQ3MTgxMDM0fQ.qZw4c00MCgJtSlFSBoOK2yxBB-apyyCQM6ASlaVMSss

########### Products ###############

###
POST http://localhost:5000/api/v1/products
Content-Type: application/json

{
  "name":"Sample Product3",
  "image":"http://www.sample.com"
}

###
GET http://localhost:5000/api/v1/products

########### OrderLines ###############

###
POST http://localhost:5000/api/v1/orderLines/6229f8d34f07b73d003e72e9
Content-Type: application/json

{
  "price":"1.99"
}

###
POST http://localhost:5000/api/v1/orderLines/6229f8e74f07b73d003e72ed
Content-Type: application/json

{
  "quantity":"4",
  "price":"2.99"
}

###
GET http://localhost:5000/api/v1/orderLines

########### Orders ###############

###
POST http://localhost:5000/api/v1/orders/6229f9524f07b73d003e72f4
Content-Type: application/json

{
  "orderLines":[
      {"_id": "6229f8df4f07b73d003e72eb"},
      {"_id": "6229f8f14f07b73d003e72ef"}
  ],
  "totalPrice":"121.99"
}

###
GET http://localhost:5000/api/v1/orders/6229f9524f07b73d003e72f4