POST http://localhost:5000/api/v1/movies HTTP/1.1
Content-Type: application/json

{
	"name": "bat man",
	"publishedYear": 2021,
	"genres": ["Horror","Comedy", "Adventures"]

}
###
POST http://localhost:5000/api/v1/users
Content-Type: application/json

{
  "username": "Rgeorge2",
  "password": "12344321",
  "firstName": "Rafael",
  "lastName": "Georgio"
}

###
GET http://localhost:5000/api/v1/users

###
GET http://localhost:5000/api/v1/movies